# PyREPL

In [ ]:
!pip install -q  langchain-experimental langchain_community langchain openai

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.4/50.4 kB 1.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.1/208.1 kB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 38.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 21.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.5/383.5 kB 14.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.4/76.4 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.0/78.0 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 318.9/318.9 kB 13.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.9/400.9 kB 17.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.6/294.6 kB 14.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.9/141.9 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 3.3 MB/s eta 0:00:00

In [ ]:
from langchain.agents import Tool
from langchain_experimental.utilities import PythonREPL
from langchain_experimental.tools.python.tool import PythonAstREPLTool

# python_repl = PythonREPL()
python_repl = PythonAstREPLTool()
#

In [ ]:
result = python_repl.run("""```python
data =(1+1)
(data, {"solution": data})
```
""")

print(type(result))
result

<class 'tuple'>

(2, {'solution': 2})

In [ ]:
import pandas as pd

# DataFrame 1: Sales Data
data1 = {
    'Product_ID': [101, 102, 103, 104],
    'Product_Name': ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
    'Price': [1000, 25, 40, 150]
}
df1 = pd.DataFrame(data1)

# DataFrame 2: Inventory Data
data2 = {
    'Product_ID': [101, 102, 104, 105],
    'Stock': [50, 200, 75, 30]
}
df2 = pd.DataFrame(data2)

# DataFrame 3: Sales Transactions
data3 = {
    'Transaction_ID': [1, 2, 3, 4],
    'Product_ID': [101, 103, 104, 102],
    'Quantity_Sold': [3, 5, 2, 10]
}
df3 = pd.DataFrame(data3)

# DataFrame 4: Customer Feedback
data4 = {
    'Product_ID': [101, 102, 103, 105],
    'Customer_Rating': [4.5, 4.0, 3.5, 4.8],
    'Feedback': ['Excellent', 'Good', 'Average', 'Great']
}
df4 = pd.DataFrame(data4)

# Printing all DataFrames to see their structures
print("DataFrame 1 - Sales Data:")
print(df1)
print("\nDataFrame 2 - Inventory Data:")
print(df2)
print("\nDataFrame 3 - Sales Transactions:")
print(df3)
print("\nDataFrame 4 - Customer Feedback:")
print(df4)

DataFrame 1 - Sales Data:
   Product_ID Product_Name  Price
0         101       Laptop   1000
1         102        Mouse     25
2         103     Keyboard     40
3         104      Monitor    150

DataFrame 2 - Inventory Data:
   Product_ID  Stock
0         101     50
1         102    200
2         104     75
3         105     30

DataFrame 3 - Sales Transactions:
   Transaction_ID  Product_ID  Quantity_Sold
0               1         101              3
1               2         103              5
2               3         104              2
3               4         102             10

DataFrame 4 - Customer Feedback:
   Product_ID  Customer_Rating   Feedback
0         101              4.5  Excellent
1         102              4.0       Good
2         103              3.5    Average
3         105              4.8      Great

In [ ]:
python_repl = PythonAstREPLTool(locals={"df": [df1]})
result = python_repl.run("""```python
df[0] = df[0].T
print(df[0])
df[0]
```
""")

print(type(result))
result

                   0      1         2        3
Product_ID       101    102       103      104
Product_Name  Laptop  Mouse  Keyboard  Monitor
Price           1000     25        40      150
<class 'pandas.core.frame.DataFrame'>

                   0      1         2        3
Product_ID       101    102       103      104
Product_Name  Laptop  Mouse  Keyboard  Monitor
Price           1000     25        40      150

In [ ]:
df1

   Product_ID Product_Name  Price
0         101       Laptop   1000
1         102        Mouse     25
2         103     Keyboard     40
3         104      Monitor    150

In [ ]:
import pandas as pd

# Assuming the 4 dataframes from the previous example are already created
dataframes = [df1, df2, df3, df4]

# Finding the common columns shared by all dataframes
common_columns = set(dataframes[0].columns)
for df in dataframes[1:]:
    common_columns.intersection_update(df.columns)

# Convert common_columns set to a list (since sets are unordered)
common_columns = list(common_columns)

# If there is a common column, proceed with merging, else print a message
if common_columns:
    # Using the first common column for merging purposes
    merge_column = common_columns[0]

    # Merging all dataframes on the found common attribute using outer join
    concise_df = dataframes[0]
    for df in dataframes[1:]:
        concise_df = pd.merge(concise_df, df, on=merge_column, how='inner')

    # Filling NaN values for easier interpretation
    concise_df.fillna('N/A', inplace=True)

    # Printing the concise DataFrame
    print("Concise DataFrame:")
    display(concise_df)
else:
    print("No common columns found to merge the dataframes.")

Concise DataFrame:

,Product_ID,Product_Name,Price,Stock,Transaction_ID,Quantity_Sold,Customer_Rating,Feedback
0,101,Laptop,1000,50,1,3,4.5,Excellent
1,102,Mouse,25,200,4,10,4.0,Good

In [ ]:
data1 = {
    'Product_ID': [101, 102, 103, 104],
    'Product_Name': ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
    'Price': [1000, 25, 40, 150]
}
df1 = pd.DataFrame(data1)

# DataFrame 2: Inventory Data
data2 = {
    'Product_ID': [101, 102, 104, 105],
    'Stock': [50, 200, 75, 30]
}
df2 = pd.DataFrame(data2)

# DataFrame 3: Sales Transactions
data3 = {
    'Transaction_ID': [1, 2, 3, 4],
    'Product_ID': [101, 103, 104, 102],
    'Quantity_Sold': [3, 5, 2, 10]
}
df3 = pd.DataFrame(data3)

# DataFrame 4: Customer Feedback
data4 = {
    'Product_ID': [101, 102, 103, 105],
    'Customer_Rating': [4.5, 4.0, 3.5, 4.8],
    'Feedback': ['Excellent', 'Good', 'Average', 'Great']
}
df4 = pd.DataFrame(data4)
python_repl = PythonAstREPLTool(locals={"dataframes": [df1,df2,df3,df4]})
result = python_repl.run("""```python
import pandas as pd
# Finding the common columns shared by all dataframes
common_columns = set(dataframes[0].columns)
for df in dataframes[1:]:
    common_columns.intersection_update(df.columns)

# Convert common_columns set to a list (since sets are unordered)
common_columns = list(common_columns)

# If there is a common column, proceed with merging, else print a message
if common_columns:
    # Using the first common column for merging purposes
    merge_column = common_columns[0]

    # Merging all dataframes on the found common attribute using outer join
    concise_df = dataframes[0]
    for df in dataframes[1:]:
        concise_df = pd.merge(concise_df, df, on=merge_column, how='inner')

    # Filling NaN values for easier interpretation
    concise_df.fillna('N/A', inplace=True)

    # Printing the concise DataFrame
    print("Concise DataFrame:")
    display(concise_df)
else:
    print("No common columns found to merge the dataframes.")
```
""")

print(type(result))
result[0]

,Product_ID,Product_Name,Price,Stock,Transaction_ID,Quantity_Sold,Customer_Rating,Feedback
0,101,Laptop,1000,50,1,3,4.5,Excellent
1,102,Mouse,25,200,4,10,4.0,Good

<class 'str'>

'C'

In [ ]:
import pandas as pd

# DataFrames initialization with unspecified column names
dataframes = [
    pd.DataFrame({
        'Product_Code': [201, 202, 203, 204],
        'Product_Name': ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
        'Price': [1000, 25, 40, 150],
        'Category': ['Electronics', 'Accessories', 'Accessories', 'Electronics'],
        'Brand': ['BrandA', 'BrandB', 'BrandB', 'BrandC']
    }),
    pd.DataFrame({
        'Product_Code': [201, 202, 204, 205],
        'Stock': [50, 200, 75, 30],
        'Supplier': ['Supplier1', 'Supplier2', 'Supplier1', 'Supplier3'],
        'Category': ['Electronics', 'Accessories', 'Electronics', 'Accessories']
    }),
    pd.DataFrame({
        'Transaction_ID': [1, 2, 3, 4],
        'Product_Code': [201, 203, 204, 202],
        'Quantity_Sold': [3, 5, 2, 10],
        'Category': ['Electronics', 'Accessories', 'Electronics', 'Accessories'],
        'Sales_Channel': ['Online', 'Store', 'Store', 'Online']
    }),
    pd.DataFrame({
        'Supplier': ['Supplier1', 'Supplier2', 'Supplier1', 'Supplier3'],
        'Customer_Rating': [4.5, 4.0, 3.5, 4.8],
        'Feedback': ['Excellent', 'Good', 'Average', 'Great'],
        'Category': ['Electronics', 'Accessories', 'Accessories', 'Accessories'],
        'Warranty': ['2 years', '1 year', '1 year', '2 years']
    }),
    pd.DataFrame({
        'Product_Code': [201, 202, 203],
        'Promotion': ['Discount', 'Clearance', 'None'],
        'Promotion_Amount': [100, 5, 0],
        'Valid_Until': ['2024-12-31', '2024-10-31', '2025-01-15']
    })
]

# Identify common columns across all DataFrames
# Perform outer join for the first three dataframes using the first common column
merged_df = dataframes[0]
for df in dataframes[1:]:
    merged_df = pd.merge(merged_df, df, how='outer')


# Filling NaN values for easier interpretation
merged_df.fillna('N/A', inplace=True)

# Display the merged DataFrame
print("Merged DataFrame after outer join:")
print(merged_df)

Merged DataFrame after outer join:
  Product_Code Product_Name   Price     Category   Brand  Stock   Supplier  \
0        201.0       Laptop  1000.0  Electronics  BrandA   50.0  Supplier1
1        202.0        Mouse    25.0  Accessories  BrandB  200.0  Supplier2
2        203.0     Keyboard    40.0  Accessories  BrandB    N/A        N/A
3        204.0      Monitor   150.0  Electronics  BrandC   75.0  Supplier1
4        205.0          N/A     N/A  Accessories     N/A   30.0  Supplier3
5          N/A          N/A     N/A  Accessories     N/A    N/A  Supplier1

  Transaction_ID Quantity_Sold Sales_Channel Customer_Rating   Feedback  \
0            1.0           3.0        Online             4.5  Excellent
1            4.0          10.0        Online             4.0       Good
2            2.0           5.0         Store             N/A        N/A
3            3.0           2.0         Store             4.5  Excellent
4            N/A           N/A           N/A             4.8      Great
5            N/A           N/A           N/A             3.5    Average

  Warranty  Promotion Promotion_Amount Valid_Until
0  2 years   Discount            100.0  2024-12-31
1   1 year  Clearance              5.0  2024-10-31
2      N/A       None              0.0  2025-01-15
3  2 years        N/A              N/A         N/A
4  2 years        N/A              N/A         N/A
5   1 year        N/A              N/A         N/A

<ipython-input-44-198c250d53e7>:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  merged_df.fillna('N/A', inplace=True)

In [ ]:
pd.merge(df1, df2, how='outer')

   Product_ID Product_Name   Price  Stock
0         101       Laptop  1000.0   50.0
1         102        Mouse    25.0  200.0
2         103     Keyboard    40.0    NaN
3         104      Monitor   150.0   75.0
4         105          NaN     NaN   30.0